"""Trocando nome da coluna price_inc_tax para price_incl_tax na MOdel ScrapperBooks

Revision ID: 299e49ae3fd3
Revises: d30c5e11ae13
Create Date: 2025-11-29 14:11:53.187208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299e49ae3fd3'
down_revision: Union[str, Sequence[str], None] = 'd30c5e11ae13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('scrapper_books')
    op.drop_table('user_acess')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_acess',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('token', sa.TEXT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scrapper_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=120), nullable=False),
    sa.Column('genre', sa.VARCHAR(length=80), nullable=False),
    sa.Column('price', sa.FLOAT(), nullable=False),
    sa.Column('availability', sa.INTEGER(), nullable=False),
    sa.Column('rating', sa.VARCHAR(length=20), nullable=False),
    sa.Column('upc', sa.VARCHAR(length=100), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=200), nullable=False),
    sa.Column('product_type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('price_excl_tax', sa.FLOAT(), nullable=False),
    sa.Column('price_inc_tax', sa.FLOAT(), nullable=False),
    sa.Column('tax', sa.FLOAT(), nullable=False),
    sa.Column('number_of_reviews', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), nullable=False),
    sa.Column('password', sa.VARCHAR(length=120), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
